name = "sre-lab-api"
main = "src/index.js"
compatibility_date = "2026-06-14"

[observability]
enabled = true

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "5ea34c7e316a4733bee1f797457e863e"

[vars]
AI_MODEL = "gpt-4.1-nano"
